### ISSUE TITLE
Working on the Hangman Project!

### ISSUE THREAD

**Issue by MenarSelamet** [Recoded-Spark-Turkey-2022/hangman-firsttime#2]
- [x] Create a function that:
        - Fetches the random words from the API 
        - Splits them into letters 
        - Pushes them into an array.
- [x] Create a function that:
        - Generates alphabets A-Z
        - Turns them to uppercase
        - Splits them into single alphabets
        - Adds them to buttons 
      
- [x] Add eventlistener that:
        - Changes the background color when clicked
        - logs the letters to the console when clicked
        - Checks if alphabet is within the random word
        - Replaces the empty span with the clicked letter if the word contains that letter

- [x] Create a function that:
        - Creates and empty span for each letter of the random words
        
- [x] Create if statements that:
       - Checks if the clicked letter is not part of the word 
       - Increases the number of wrong guesses with each wrong guess
       - Inserts an image of the hanged man 
       - When last piece of the hangman is inserted pops up a Game Over div
      
- [x] Create a Play again button.

- [x] Add hint button that:
      - When clicked inserts a hint that was fetched from an API of dictionary that brings meanings of words.
      
- [x] Add if statement that:
      - Pushes the letters to the empty spans if the guesses letter is correct.
      - Shows part of the image on the screen if the guessed letter is wrong.

**Comment by niranjana1997** [comment]
Is it alright if I contribute to this project?

**Comment by MenarSelamet** [comment]
> Is it alright if I contribute to this project?

Hey there, this is actually a team project that we're working on in a bootcamp, so we're not really allowed to get help. butt butt we could always connect afterwards to see how we can modify it ? I'll connect with you on linkedIn :)
